# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 6000000
  contracts:
  - name: MedSynapseConsent
    address:
    - 0x05133bC59e34413F683Cc336A26f215b3261a51F
    handler: src/EventHandlers.ts
    events:
    - event: ConsentCreated(bytes32 indexed consentId, address indexed contributor, string dataHash, string dataType, string description)
    - event: ConsentRevoked(bytes32 indexed consentId, address indexed contributor)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: ResearchApproved(bytes32 indexed consentId, address indexed researcher)
    - event: ResearchRequested(bytes32 indexed consentId, address indexed researcher, string purpose)
unordered_multichain_mode: true
preload_handlers: true
