[build]
  base = "frontend"
  command = "pnpm install && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.16.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

