[build]
  command = "cd frontend && pnpm install && pnpm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

